### ISSUE TITLE
led type and pinout? 

### ISSUE THREAD

**Issue by opus506** [loicortola/led-controller#1]
What type of LEDs is this designed for?
ws2812b, 12v rgb, etc.

what or where is the pinout setup?

**Comment by loicortola** [comment]
Hello @opus506 
this is made for 5050 (aka 12v RGB) LEDs.
The pinout is easy, although requires external components (resistors and transistors) to ensure enough current drawn to the LEDs.
I haven't sent the schematics for now, would you be interested in it?

**Comment by opus506** [comment]
I would love it! I really like how you've set things to work as
multi-master and multi-node objects. Well done my friend

**Comment by loicortola** [comment]
Thanks a lot ;)

There is still some work that can be made on the Android App (I really coded it in a few hours to have something working out of the box) but it works well.
Also, I implemented generic command patterns so that we can support literally any kind of IoT equipment in the future.

If you are a developer, know that contributions are welcome ;)

I am not good with Eagle schematics yet, so I just drew the circuit.
For 3.3V, I used a regular 3.3V voltage regulator which draws power directly from the 12V input.
![img_20171015_204601](https://user-images.githubusercontent.com/2526081/31587922-9dce7458-b1ea-11e7-84ca-77c8ab7e74f7.jpg)

 * I use PIN 5 for red, PIN 4 for green, and PIN 15 for blue.
 * Each pin is connected to the base of a NPN transistor
 * The emitter of each transistor is connected to GND
 * The collector of each transistor is connected to a pull-up transistor of 200k ohm (+12V) and to the related input of the led strip.

The only thing I haven't solved yet (poor electronics skills I guess) is high thermal dissipation of the 3.3V power-supply. I think a step-down power converter would be more appropriate than a simple 3.3V voltage regulator. (It doesn't matter though, the device works perfectly, I just think efficiency and power consumption could be slightly lower if using a step-down).

**Comment by opus506** [comment]
I built a prototype board for this exact purpose a while back. 2n2222a
transistors give each channel 800mah, which can fork into 3 line rails if
desired. Pretty sure its the same except for the placement of the resistors.

![img_20171015_170048](https://user-images.githubusercontent.com/15916991/31588887-c8269594-b1ce-11e7-9267-5dfecfc35bb7.jpg)
![img_20171015_170100](https://user-images.githubusercontent.com/15916991/31588888-c9e220c4-b1ce-11e7-8f5d-32aac3e6ad36.jpg)
![img_20171015_170107](https://user-images.githubusercontent.com/15916991/31588889-cb11740e-b1ce-11e7-8ba4-a7700243962a.jpg)
![img_20171015_170706](https://user-images.githubusercontent.com/15916991/31588890-cc873d32-b1ce-11e7-85cf-4725aa4a79c5.jpg)

**Comment by loicortola** [comment]
Hahaha awesome!
I'm currently looking at other circuits (because I want to make the transition from Wifi to ZigBee Light Link compatible, in order to use the controller with Philips HUE, LiFx and other Home automation device), and the guys are using MOSFETs instead, as those can reach more current.
I think the source of heat and power-loss is the stepdown though (for Arduino).

**Comment by loicortola** [comment]
https://learn.adafruit.com/rgb-led-strips/usage

**Comment by loicortola** [comment]
In the end, that's what it would look like:

![sch](https://user-images.githubusercontent.com/2526081/31793629-1033448c-b520-11e7-86b0-d83950564a9b.png)

**Comment by loicortola** [comment]
R1=R2=R3=R4=10k

**Comment by loicortola** [comment]
Finished PCB prototype.
Here is the final look :
![1-board](https://user-images.githubusercontent.com/2526081/32481732-f2cd729a-c394-11e7-9c0e-3362bdb697a3.jpg)

![2-board-lego](https://user-images.githubusercontent.com/2526081/32481730-f266aa7e-c394-11e7-9e53-90121dcfe10c.jpg)

![3-controller](https://user-images.githubusercontent.com/2526081/32481731-f27e6c36-c394-11e7-8093-6390ea610ac0.jpg)

**Comment by opus506** [comment]
The area behind the back of the antenna is supposed to be air gaped
according to espressif. Everything looks great though.

**Comment by loicortola** [comment]
I consider this issue resolved. Take a look at the updated schematics and board :)
